apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kubepkg.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "kubepkg.labels" . | nindent 4 }}
rules:
  - apiGroups: [{{ .Values.apiGroup | quote }}]
    resources: [packages, packagesources, packagerevisions, repositories, clusters, packagesets]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [{{ .Values.apiGroup | quote }}]
    resources: [packages/status, packagesources/status, packagerevisions/status, repositories/status, clusters/status, packagesets/status, packages/finalizers, packagesets/finalizers]
    verbs: [get, update, patch]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [get, list, watch, update, patch, delete]
  # After moving objects to the storage version, the operator records
  # that only that version is stored.
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions/status]
    verbs: [update]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [get, list, watch, create, update, patch]
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [helm.toolkit.fluxcd.io]
    resources: [helmreleases]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [source.toolkit.fluxcd.io]
    resources: [ocirepositories, helmrepositories]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [argoproj.io]
    resources: [applications]
    verbs: [get, list, watch, create, update, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "kubepkg.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
{{- if .Values.clusterAdmin }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-cluster-admin
  labels: {{- include "kubepkg.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
